version: '2.1'
services:
  postgres:
    image: postgres:latest
    container_name: postgress_image
    restart: always
    environment:
      POSTGRES_DB: banpay
      POSTGRES_USER: orutra971
      POSTGRES_PASSWORD: fc4kWgceSrtCRebbJyK7bBYjwq5CjNB4
    ports:
      - "5432:5432"
    volumes:
      - ./migrations/1_db_init.up.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - spring-cloud-network
  banpay-challenge:
    container_name: banpay-challenge
    depends_on:
      - postgres
    build:
      context: banpay-challenge
      dockerfile: Dockerfile
    image: banpay-challenge:latest
    ports:
      - "8080:8080"
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge