name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write

    steps:
    - uses: actions/checkout@v4    
    - name: Set Up OpenJDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'oracle' # See 'Supported distributions' for available options
        java-version: '21'
        cache: maven
    - name: Build with Maven
      run: mvn -B package -Pprod
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: 'Build Inventory Image'
      run: |
        docker build . --tag ghcr.io/orutra971/banpay-challenge:latest
        docker push ghcr.io/orutra971/banpay-challenge:latest
