name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set Up OpenJDK 21
    - uses: actions/setup-java@v4
      with:
        distribution: 'oracle' # See 'Supported distributions' for available options
        java-version: '21'
        cache: maven
    - name: Build with Maven
      run: mvn -B package -Pprod
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag banpay-challenge:latest
